import type { Metadata } from "next";
import Navbar from "@/components/Layout/navbar";
import { Footer } from "@/components/Layout/footer";
import "../../styles/globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <head>
            <link
                href="https://api.fontshare.com/v2/css?f[]=satoshi@400&display=swap"
                rel="stylesheet"
            />
            <title></title>
        </head>

        <body className="antialiased font-satoshi flex flex-col">
        <div>
        {/* Navbar */}

        <Navbar />

        {/* Main content */}
        <div className="h-auto">{children}</div>

        {/* Footer */}
        <footer>
            <Footer />
        </footer>
        </div>
        </body>
        </html>
    );
}
